"""
Django settings for vulfocus project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import docker
import datetime
import redis
from django.core.management import utils

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = os.environ['SECRET_KEY']
except:
    SECRET_KEY = utils.get_random_secret_key()
    os.environ['SECRET_KEY'] = SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = "user.UserProfile"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition
ALLOWED_IMG_SUFFIX = ["jpg", "jpeg", "png"]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'user',
    'corsheaders',
    'dockerapi',
    'network',
    'tasks',
    'layout_image',
    'captcha',
    'notifications',
    'notice',
]

REDIS_HOST = os.environ.get('REDIS_HOST')
if not REDIS_HOST or REDIS_HOST == '':
    REDIS_HOST = "127.0.0.1"

# redis port
REDIS_PORT = os.environ.get('REDIS_PORT')
if not REDIS_PORT or REDIS_PORT == '' or REDIS_PORT == 0:
    REDIS_PORT = "6379"

# redis pass
REDIS_PASS = os.environ.get('REDIS_PASS')
if not REDIS_PASS or REDIS_PASS == '':
    REDIS_PASS = ""

if REDIS_PASS:
    CELERY_BROKER_URL = "redis://:%s@%s:%s/0" % (REDIS_PASS, str(REDIS_HOST), str(REDIS_PORT))
    REDIS_POOL = redis.ConnectionPool(host=REDIS_HOST, port=int(REDIS_PORT), password=REDIS_PASS, decode_responses=True,
                                      db=1)
else:
    CELERY_BROKER_URL = 'redis://%s:%s/0' % (REDIS_HOST, str(REDIS_PORT))
    REDIS_POOL = redis.ConnectionPool(host=REDIS_HOST, port=int(REDIS_PORT), decode_responses=True, db=1)

if REDIS_PASS:
    REDIS_IMG = redis.Redis(host=REDIS_HOST, port=int(REDIS_PORT), password=REDIS_PASS, db=6, decode_responses=True)
    REDIS_USER_CACHE = redis.Redis(host=REDIS_HOST, port=int(REDIS_PORT), password=REDIS_PASS, db=7, decode_responses=True)
else:
    REDIS_IMG = redis.Redis(host=REDIS_HOST, port=int(REDIS_PORT), db=6, decode_responses=True)
    REDIS_USER_CACHE = redis.Redis(host=REDIS_HOST, port=int(REDIS_PORT), db=7, decode_responses=True)

CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:9527",
]
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
    'AUTH_HEADER_TYPES': ('BMH',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


ROOT_URLCONF = 'vulfocus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vulfocus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# 默认启动容器最长时间为 60s，可根据实际情况调整
DOCKER_CONTAINER_TIME = 60

try:
    # DOCKER_URL tcp://127.0.0.1:2375 or unix://var/run/docker.sock
    # DOCKER_URL = "tcp://192.168.87.136:2375"
    DOCKER_URL = os.environ['DOCKER_URL']
except:
    DOCKER_URL = "unix://var/run/docker.sock"

client = None
api_docker_client = None
try:
    if DOCKER_URL.startswith("unix:"):
        client = docker.DockerClient(base_url=DOCKER_URL)
        api_docker_client = docker.APIClient(base_url=DOCKER_URL)
    else:
        client = docker.DockerClient(DOCKER_URL)
        api_docker_client = docker.APIClient(base_url=DOCKER_URL)
    try:
        client.ping()
        print(f"Successfully connected to Docker at {DOCKER_URL}")
    except Exception as ping_error:
        print(f"Docker client created but ping failed: {ping_error}")
        client = None
        api_docker_client = None
except Exception as e:
    print(f"Failed to connect to Docker at {DOCKER_URL}: {e}")

try:
    """
    设置 docker-compose 连接
    """
    os.environ['DOCKER_HOST'] = DOCKER_URL
except Exception as e:
    pass


# 靶场绑定 IP，提供用户访问靶场与 Docker 服务IP保持一致。
VUL_IP = ""
try:
    if os.environ['VUL_IP']:
        VUL_IP = os.environ['VUL_IP']
except Exception as e:
    pass

DOCKER_COMPOSE = os.path.join(BASE_DIR, "docker-compose")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

EMAIL_HOST = ""
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
try:
    if os.environ['EMAIL_HOST']:
        EMAIL_HOST = os.environ['EMAIL_HOST']
    if os.environ['EMAIL_HOST_USER']:
        EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
    if os.environ['EMAIL_HOST_PASSWORD']:
        EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
except Exception as e:
    pass

#邮箱配置
EMAIL_HOST = EMAIL_HOST
EMAIL_PORT = 465
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_USE_SSL = True
EMAIL_FROM = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 字母验证码设置
CAPTCHA_IMAGE_SIZE = (90, 45)
CAPTCHA_LENGTH = 4
CAPTCHA_TIMEOUT = 1


COMPOSE_ZIP_PATH = os.path.join(BASE_DIR, "compose-zip-store")
# docker-compose文件下载格式
DOWNLOAD_FILE_TYPE = ".zip"
UPLOAD_ZIP_PATH = os.path.join(BASE_DIR, "upload_zip")